### ISSUE TITLE
Previous error of negative new daily cases still reflected in total cases

### ISSUE THREAD

**Issue by dimarkov** [victorvicpal/COVID19_es#19]
A brief follow up on the previous issue which you just closed. 

I think that the negative values in new daily cases ('nuevos'), which you fixed now (thank again!),  is somehow still reflected in the total cases ('casos') column. 

When I plot total cases over time for whole Spain I still see a sudden drop in value towards the end, which should not happen as total cases should increase over time.

**Comment by victorvicpal** [comment]
Could you tell me the specific date when the drop happens?
I have a feeling that this problem could be due to how Madrid and Cataluña were delivering their data during a specific week.

**Comment by dimarkov** [comment]
So, the date with negative change in cases corresponds to  2020-04-24. But there are few more days with inconsistencies between daily cases which one gets directly from 'nuevos' column, and 
daily cases which one would estimate from casos column, with casos(t) - casos(t-1). Please see attached figure.

![fig](https://user-images.githubusercontent.com/5038100/81504557-4ff9e080-92ea-11ea-9da1-00df3f136e93.png)

I looked only at overall national data but I could try to identify problematic regions, if there is only few of them.

**Comment by dimarkov** [comment]
If I look at regional data the curves are matched only for Canarias, Cataluña, and Melilla. In all other cases I see discrepancy between nuevos(t) and casos(t) - casos(t-1), on at least one day, sometimes even more.

**Comment by victorvicpal** [comment]
Thanks again for pointing out these inconsistencies.

I reuploaded a new csv file, could you check if the issue still persists?

**Comment by dimarkov** [comment]
Unfortunately it got worse somehow

![fig](https://user-images.githubusercontent.com/5038100/81509659-80eb0d00-930c-11ea-9ce7-36744f5bcfd7.png)

Now initial values for 'nuevos' column (orange line) are missing (most seem to be zero) although number of cases is increasing. Similarly, a new small negative trough shows up on 2020-03-07 if one uses casos(t) - casos(t-1) to estimate the daily cases (blue line).

**Comment by victorvicpal** [comment]
It's funny because the only changes I did where just transfer the original ministry data and putting away my changes.
I guess there will be footnotes on the official PDFs for these specific days.
Let me check.

The nans at the beginning can be fixed as you already did. I'm more worried about the other changes.

I will try to look into it.

**Comment by victorvicpal** [comment]
I'm afraid I won't have time this week to check it (I have a lot of workloads).
I have a feeling that this errors are related to the original data, not the code.
The problem is that all PDF footnotes are written in Spanish so I do not know if you will be able to translate it.

I keep it open while waiting for finding the bug.

Sorry :(

**Comment by dimarkov** [comment]
No problem. It is very likely that the problem is with the original data. I checked also John Hopkins repo and their data has the same problem with daily cases and total cases for Spain.
